### PR TITLE
Fix UI inconsistances 

### PR DESCRIPTION
**Pull request by dnuwa**
#### What does this PR do?
- Update the User interface
#### Description of Task to be completed?
-  [x] give every card a color to clearly show the borders of the card
 - [x] align login anchor tags in the center of the div on hover
-  [x] bug fix on signup and login links
-  [x] add a landing page
-  [x] make the card clickable
- [x] add `my adverts` link to display only adverts for the logged in user
- [x] choose and add one extra feature
- [x] separate CSS files
#### How should this be manually tested?
- N/A
#### Any background context you want to provide?
- N/A
#### What are the relevant pivotal tracker stories?
- [#167148011](https://www.pivotaltracker.com/story/show/167148011)
#### Screenshots (if appropriate)
`give every card a color to clearly show the borders of the card and make the card clickable`
Screenshot (45)

`align login anchor tags in the center of the div on hover`
Screenshot (46)

`bug fix on signup and login links`
Screenshot (47)

`add my adverts link to display only adverts for the logged in user`
Screenshot (49)

`add a landing page`
Screenshot (50)

### CODE REVIEW

**Comment by Oluwasegun-AA** [comment]
please reduce the side of this to about 1/3 of its original size and ensure it remains centred 
image

**Comment by Oluwasegun-AA** [comment]
also, please reduce the thickness of the green bottom border by half or just give it a 1px thickness on hover 
image

**Comment by Oluwasegun-AA** [comment]
Good job implementing the feedback as swift as possible. please implement these and get back to me.

**Comment by dnuwa** [comment]
> please reduce the side of this to about 1/3 of its original size and ensure it remains centred
> image

this has been worked as shown below
Screenshot (53)

**Comment by dnuwa** [comment]
> also, please reduce the thickness of the green bottom border by half or just give it a 1px thickness on hover
> image

this has also been worked on. see screenshot below.
Screenshot (54)

**Comment by Oluwasegun-AA** [comment]
please go ahead and merge

**Pull request merged**
